on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        CHESS_SERVER_HTTP: ${{ secrets.CHESS_SERVER_HTTP }}
        CHESS_SERVER_WS: ${{ secrets.CHESS_SERVER_WS }}

    - name: Deploy
      uses: psychout09/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
